### ISSUE TITLE
When to release the model？

### ISSUE THREAD

**Issue by StevenTony611** [ryanxingql/winner-ntire22-vqe#2]
When to release the model？ We are interested in your model， but we find not released this.

**Comment by ryanxingql** [comment]
Hi,

This work is done during my internship, and thus I have no right to release the model without permission.
If I am permitted to release the model, I will notify you here.

I have detailed the implementation in my blog. If you have any questions, please get in touch with me.

**Comment by ryanxingql** [comment]
Hi @StevenTony611,

I get permission to release models. Sorry for being late.

Models: https://github.com/ryanxingql/winner-ntire22-vqe/releases/tag/v1.0
README: https://github.com/ryanxingql/winner-ntire22-vqe/blob/main/README_test.md
