### ISSUE TITLE
missing stage2 model files

### ISSUE THREAD

**Issue by onurbarut** [ryanxingql/winner-ntire22-vqe#5]
Hi,

Uploaded files extract iter_1000.pth and iter_16000.pth for track 1, iter_3000.pth for track 2, and iter_8000.pth and iter_11000.pth for track 3. However, your script in Readme_test.md says 9000_G.pth for stage 2 of track 1, 15000_G.pth for stage 2 of track 2, and 15000_G.pth for stage 2 of track 3, which seems to be missing. Maybe you missed to upload them?

**Comment by ryanxingql** [comment]
You should check the "stage2.zip". Those pth files are in "stage2/work_dirs".

**Comment by onurbarut** [comment]
got it, thanks for the heads up!
